/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20017 {
    /// match_id
    #[serde(rename = "match_id", skip_serializing_if = "Option::is_none")]
    pub match_id: Option<i32>,
    /// match_seq_num
    #[serde(rename = "match_seq_num", skip_serializing_if = "Option::is_none")]
    pub match_seq_num: Option<i32>,
    /// Boolean indicating whether Radiant won the match
    #[serde(rename = "radiant_win", skip_serializing_if = "Option::is_none")]
    pub radiant_win: Option<bool>,
    /// start_time
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i32>,
    /// Duration of the game in seconds
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// radiant_team
    #[serde(rename = "radiant_team", skip_serializing_if = "Option::is_none")]
    pub radiant_team: Option<String>,
    /// dire_team
    #[serde(rename = "dire_team", skip_serializing_if = "Option::is_none")]
    pub dire_team: Option<String>,
}

impl InlineResponse20017 {
    pub fn new() -> InlineResponse20017 {
        InlineResponse20017 {
            match_id: None,
            match_seq_num: None,
            radiant_win: None,
            start_time: None,
            duration: None,
            radiant_team: None,
            dire_team: None,
        }
    }
}


