/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20024 {
    /// Numeric identifier for the hero object
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Dota hero command name, e.g. 'npc_dota_hero_antimage'
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Hero name, e.g. 'Anti-Mage'
    #[serde(rename = "localized_name", skip_serializing_if = "Option::is_none")]
    pub localized_name: Option<String>,
    /// Hero primary shorthand attribute name, e.g. 'agi'
    #[serde(rename = "primary_attr", skip_serializing_if = "Option::is_none")]
    pub primary_attr: Option<String>,
    /// Hero attack type, either 'Melee' or 'Ranged'
    #[serde(rename = "attack_type", skip_serializing_if = "Option::is_none")]
    pub attack_type: Option<String>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<String>>,
}

impl InlineResponse20024 {
    pub fn new() -> InlineResponse20024 {
        InlineResponse20024 {
            id: None,
            name: None,
            localized_name: None,
            primary_attr: None,
            attack_type: None,
            roles: None,
        }
    }
}


