/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2001 {
    /// account_id
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<f32>,
    /// Integer indicating the rank/medal of the player
    #[serde(rename = "rank_tier", skip_serializing_if = "Option::is_none")]
    pub rank_tier: Option<f32>,
    /// Indicates if we were unable to fetch full history for this player due to privacy settings
    #[serde(rename = "fh_unavailable", skip_serializing_if = "Option::is_none")]
    pub fh_unavailable: Option<bool>,
}

impl InlineResponse2001 {
    pub fn new() -> InlineResponse2001 {
        InlineResponse2001 {
            account_id: None,
            rank_tier: None,
            fh_unavailable: None,
        }
    }
}


