/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2002Profile : profile



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2002Profile {
    /// account_id
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i32>,
    /// personaname
    #[serde(rename = "personaname", skip_serializing_if = "Option::is_none")]
    pub personaname: Option<String>,
    /// name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Boolean indicating status of current Dota Plus subscription
    #[serde(rename = "plus", skip_serializing_if = "Option::is_none")]
    pub plus: Option<bool>,
    /// cheese
    #[serde(rename = "cheese", skip_serializing_if = "Option::is_none")]
    pub cheese: Option<i32>,
    /// steamid
    #[serde(rename = "steamid", skip_serializing_if = "Option::is_none")]
    pub steamid: Option<String>,
    /// avatar
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// avatarmedium
    #[serde(rename = "avatarmedium", skip_serializing_if = "Option::is_none")]
    pub avatarmedium: Option<String>,
    /// avatarfull
    #[serde(rename = "avatarfull", skip_serializing_if = "Option::is_none")]
    pub avatarfull: Option<String>,
    /// profileurl
    #[serde(rename = "profileurl", skip_serializing_if = "Option::is_none")]
    pub profileurl: Option<String>,
    /// last_login
    #[serde(rename = "last_login", skip_serializing_if = "Option::is_none")]
    pub last_login: Option<String>,
    /// loccountrycode
    #[serde(rename = "loccountrycode", skip_serializing_if = "Option::is_none")]
    pub loccountrycode: Option<String>,
    /// Boolean indicating if the user contributed to the development of OpenDota
    #[serde(rename = "is_contributor", skip_serializing_if = "Option::is_none")]
    pub is_contributor: Option<bool>,
}

impl InlineResponse2002Profile {
    /// profile
    pub fn new() -> InlineResponse2002Profile {
        InlineResponse2002Profile {
            account_id: None,
            personaname: None,
            name: None,
            plus: None,
            cheese: None,
            steamid: None,
            avatar: None,
            avatarmedium: None,
            avatarfull: None,
            profileurl: None,
            last_login: None,
            loccountrycode: None,
            is_contributor: None,
        }
    }
}


