/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2005 : Object containing information on the match



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    /// Match ID
    #[serde(rename = "match_id", skip_serializing_if = "Option::is_none")]
    pub match_id: Option<i32>,
    /// Which slot the player is in. 0-127 are Radiant, 128-255 are Dire
    #[serde(rename = "player_slot", skip_serializing_if = "Option::is_none")]
    pub player_slot: Option<i32>,
    /// Boolean indicating whether Radiant won the match
    #[serde(rename = "radiant_win", skip_serializing_if = "Option::is_none")]
    pub radiant_win: Option<bool>,
    /// Duration of the game in seconds
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json
    #[serde(rename = "game_mode", skip_serializing_if = "Option::is_none")]
    pub game_mode: Option<i32>,
    /// Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json
    #[serde(rename = "lobby_type", skip_serializing_if = "Option::is_none")]
    pub lobby_type: Option<i32>,
    /// The ID value of the hero played
    #[serde(rename = "hero_id", skip_serializing_if = "Option::is_none")]
    pub hero_id: Option<i32>,
    /// Time the game started in seconds since 1970
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i32>,
    /// version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// Total kills the player had at the end of the game
    #[serde(rename = "kills", skip_serializing_if = "Option::is_none")]
    pub kills: Option<i32>,
    /// Total deaths the player had at the end of the game
    #[serde(rename = "deaths", skip_serializing_if = "Option::is_none")]
    pub deaths: Option<i32>,
    /// Total assists the player had at the end of the game
    #[serde(rename = "assists", skip_serializing_if = "Option::is_none")]
    pub assists: Option<i32>,
    /// Skill bracket assigned by Valve (Normal, High, Very High)
    #[serde(rename = "skill", skip_serializing_if = "Option::is_none")]
    pub skill: Option<i32>,
    /// Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned
    #[serde(rename = "leaver_status", skip_serializing_if = "Option::is_none")]
    pub leaver_status: Option<i32>,
    /// Size of the player's party
    #[serde(rename = "party_size", skip_serializing_if = "Option::is_none")]
    pub party_size: Option<i32>,
}

impl InlineResponse2005 {
    /// Object containing information on the match
    pub fn new() -> InlineResponse2005 {
        InlineResponse2005 {
            match_id: None,
            player_slot: None,
            radiant_win: None,
            duration: None,
            game_mode: None,
            lobby_type: None,
            hero_id: None,
            start_time: None,
            version: None,
            kills: None,
            deaths: None,
            assists: None,
            skill: None,
            leaver_status: None,
            party_size: None,
        }
    }
}


