/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse20028LateGameItems : Items bought at least 25 min after game started, with cost at least 4000



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20028LateGameItems {
    /// Number of item bought
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<i32>,
}

impl InlineResponse20028LateGameItems {
    /// Items bought at least 25 min after game started, with cost at least 4000
    pub fn new() -> InlineResponse20028LateGameItems {
        InlineResponse20028LateGameItems {
            item: None,
        }
    }
}


