/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20014 {
    /// The ID value of the hero played
    #[serde(rename = "hero_id", skip_serializing_if = "Option::is_none")]
    pub hero_id: Option<String>,
    /// hero_score
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// percent_rank
    #[serde(rename = "percent_rank", skip_serializing_if = "Option::is_none")]
    pub percent_rank: Option<f32>,
    /// numeric_rank
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<i32>,
}

impl InlineResponse20014 {
    pub fn new() -> InlineResponse20014 {
        InlineResponse20014 {
            hero_id: None,
            score: None,
            percent_rank: None,
            card: None,
        }
    }
}


