/*
 * OpenDota API
 *
 * # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse20020CountryMmr : country_mmr



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20020CountryMmr {
    /// command
    #[serde(rename = "commmand", skip_serializing_if = "Option::is_none")]
    pub commmand: Option<String>,
    /// rowCount
    #[serde(rename = "rowCount", skip_serializing_if = "Option::is_none")]
    pub row_count: Option<i32>,
    /// rows
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<crate::models::InlineResponse20020CountryMmrRows>>,
    /// fields
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<crate::models::InlineResponse20020CountryMmrFields>>,
    /// rowAsArray
    #[serde(rename = "rowAsArray", skip_serializing_if = "Option::is_none")]
    pub row_as_array: Option<bool>,
}

impl InlineResponse20020CountryMmr {
    /// country_mmr
    pub fn new() -> InlineResponse20020CountryMmr {
        InlineResponse20020CountryMmr {
            commmand: None,
            row_count: None,
            rows: None,
            fields: None,
            row_as_array: None,
        }
    }
}


